# Generated by Django 5.1.7 on 2025-06-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time club data was updated'),
        ),
        migrations.AddField(
            model_name='club',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly savings target for the club', max_digits=12),
        ),
    ]
