# Generated by Django 5.1.7 on 2025-06-18 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0002_club_last_updated_club_monthly_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFixedSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fixed', models.DecimalField(decimal_places=2, help_text='Amount to be fixed', max_digits=12)),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (e.g., 10.0 for 10%)')),
                ('maturity_months', models.PositiveIntegerField(default=8, help_text='Number of months for maturity')),
                ('date_fixed', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fixed savings is still active')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_savings', to='mcs.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fixed_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
