# Generated by Django 5.1.7 on 2025-06-18 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0003_clubfixedsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfixedsavings',
            name='date_fixed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
