# Generated by Django 5.1.7 on 2025-06-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0004_alter_clubfixedsavings_date_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clubfixedsavings',
            name='amount_fixed',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='clubfixedsavings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clubfixedsavings',
            name='maturity_months',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='clubtransaction',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mcs.club'),
        ),
    ]
