# Generated by Django 5.1.7 on 2025-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0005_alter_club_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubfixedsavings',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number for this fixed savings', max_length=20, null=True),
        ),
    ]
