# Generated by Django 5.1.7 on 2025-06-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0007_clubevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtransaction',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number for this transaction', max_length=20, null=True),
        ),
    ]
