# Generated by Django 5.1.7 on 2025-06-25 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0008_clubtransaction_receipt_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': '52 WSC Investment', 'verbose_name_plural': '52 WSC Investments'},
        ),
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-date_saved'], 'verbose_name': '52 WSC Savings Transaction', 'verbose_name_plural': '52 WSC Savings Transactions'},
        ),
        migrations.CreateModel(
            name='IndividualUserFixedSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text="User's unique account number", max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Initial amount invested', max_digits=12)),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (e.g., 5.25 for 5.25%)')),
                ('maturity_period', models.PositiveIntegerField(help_text='Duration in months (6, 12, 24, etc.)')),
                ('date_fixed', models.DateField(default=django.utils.timezone.now, help_text='When the investment was made')),
                ('maturity_date', models.DateField(help_text='When the investment matures')),
                ('compounding_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('expected_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_earned_so_far', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('matured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maturity_option', models.CharField(choices=[('withdraw', 'Withdraw'), ('reinvest', 'Reinvest'), ('partial', 'Partial Withdrawal')], default='withdraw', max_length=20)),
                ('reinvestment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_interest_credit_date', models.DateField(blank=True, null=True)),
                ('total_interest_credited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_savings', to='mcs.userprofile')),
            ],
            options={
                'verbose_name': 'User Fixed Savings',
                'verbose_name_plural': 'User Fixed Savings',
                'ordering': ['-date_fixed'],
            },
        ),
    ]
