# Generated by Django 5.1.7 on 2025-07-01 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0009_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualuserfixedsavings',
            options={'ordering': ['-date_fixed'], 'verbose_name': 'Individual User Fixed Savings', 'verbose_name_plural': 'Individual User Fixed Savings'},
        ),
        migrations.AddField(
            model_name='individualuserfixedsavings',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reinvestment', 'Reinvestment')], default='deposit', help_text='Type of transaction for this fixed savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubfixedsavings',
            name='date_fixed',
            field=models.DateField(default=datetime.date.today, help_text='When the investment was made'),
        ),
        migrations.AlterField(
            model_name='individualuserfixedsavings',
            name='date_fixed',
            field=models.DateField(default=datetime.date.today, help_text='When the investment was made'),
        ),
        migrations.AlterField(
            model_name='individualuserfixedsavings',
            name='interest_rate',
            field=models.FloatField(default=12.75, help_text='Annual interest rate (e.g., 12.75 for 12.75%)'),
        ),
        migrations.AlterField(
            model_name='individualuserfixedsavings',
            name='maturity_period',
            field=models.PositiveIntegerField(default=8, help_text='Duration in months (6, 12, 24, etc.)'),
        ),
    ]
