# Generated by Django 5.1.7 on 2025-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0011_goatfarmingpackage_managementfeetier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goatfarmingpackage',
            options={'ordering': ['total_package_amount'], 'verbose_name': 'Goat Farming Package', 'verbose_name_plural': 'Goat Farming Packages'},
        ),
        migrations.RemoveField(
            model_name='goatfarminginvestment',
            name='total_goats_expected',
        ),
        migrations.RemoveField(
            model_name='goatfarminginvestment',
            name='total_goats_received',
        ),
        migrations.RemoveField(
            model_name='goatfarmingpackage',
            name='expected_returns',
        ),
        migrations.RemoveField(
            model_name='goatfarmingpackage',
            name='investment_amount',
        ),
        migrations.AddField(
            model_name='goatfarminginvestment',
            name='initial_goats_received',
            field=models.PositiveIntegerField(default=0, help_text='Initial goats received from package'),
        ),
        migrations.AddField(
            model_name='goatfarminginvestment',
            name='offspring_received',
            field=models.PositiveIntegerField(default=0, help_text='Offspring received so far'),
        ),
        migrations.AddField(
            model_name='goatfarminginvestment',
            name='total_goats_current',
            field=models.PositiveIntegerField(default=0, help_text='Total goats currently owned'),
        ),
        migrations.AddField(
            model_name='goatfarmingpackage',
            name='expected_offspring_in_one_year',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of offspring after 1 year of breeding'),
        ),
        migrations.AddField(
            model_name='goatfarmingpackage',
            name='management_fee_goat_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of goats this management fee covers'),
        ),
        migrations.AddField(
            model_name='goatfarmingpackage',
            name='total_package_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total investment amount for the entire package', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goatfarminginvestment',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount invested (should match package total_package_amount)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goatfarmingpackage',
            name='breeding_period_months',
            field=models.PositiveIntegerField(default=12, help_text='Expected breeding period in months (default 1 year)'),
        ),
        migrations.AlterField(
            model_name='goatfarmingpackage',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, help_text='Annual management fee for this package', max_digits=12),
        ),
        migrations.AlterField(
            model_name='goatfarmingpackage',
            name='number_of_female_goats',
            field=models.PositiveIntegerField(help_text='Number of female goats included in the package'),
        ),
        migrations.AlterField(
            model_name='goatfarmingpackage',
            name='number_of_male_goats',
            field=models.PositiveIntegerField(default=0, help_text='Number of male goats included in the package'),
        ),
    ]
