# Generated by Django 5.1.7 on 2025-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0012_alter_goatfarmingpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goatfarminginvestment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number for the initial investment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goatfarmingpackage',
            name='total_package_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total investment amount for the entire package', max_digits=12),
        ),
    ]
